In [2]:
#Create a null vector of size 10 but the fifth value which is 1
import numpy as np
vec = np.zeros(10)
vec[5]=1
print(vec)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [4]:
#Create a vector with values ranging from 10 to 49.
vec = np.arange(10,49)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [8]:
#Create a 3x3 matrix with values ranging from 0 to 8
vec = np.arange(9).reshape(3,3)
print(vec)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
z=np.nonzero([1,2,0,0,4,0])
print(z)

(array([0, 1, 4], dtype=int64),)


In [13]:
#Create a 10x10 array with random values and find the minimum and maximum values.
z= np.random.random((10,10))
print('Minimum value is:',z.min())
print('Maximum value is:',z.max())

Minimum value is: 0.005052098114638803
Maximum value is: 0.9891940335920829


In [18]:
#Create a random vector of size 30 and find the mean value.
z = np.random.random(30)
m = z.mean()
print(m)

0.5783421228977549
